login/login/urls.py
from django.contrib import admin
from django.urls import path,include
from login_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('login_app/',include('login_app.urls')),
    path('user_logout/',views.user_logout,name="user_logout")
]

login/login_app/urls.py
from django.urls import path
from login_app import views

app_name = 'login_app'

urlpatterns = [
    path('register/',views.register,name="register"),
    path('user_login/',views.user_login,name="user_login")
]

login/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
    

login/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username','password','email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

login/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserProfileInfoForm

from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'loginapp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            

            if 'profile_pic' in request.FILES:
                profile.profile_pic =  request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(profile_form.errors,user_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'loginapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account not active!')

        else:
            print("Login Failed!")
            print("Username : ",username,"  Password : ",password)
            return HttpResponse("Invalid Credentials!")

    else:
        return render(request,'loginapp/login.html',{})

        

                

login/templates/loginapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta chrset="utf-8">
        <title>Home</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class='navbar navbar-default navbar-statictop'>
            <div class="container">
                <ul class='nav navbar-nav'>
                    <li><a class='navbar-brand' href='{% url 'index' %}'>HOME</a></li>
                    <li><a class='navbar-link' href='{% url 'admin:index' %}'>Admin</a></li>
                    <li><a class='navbar-link' href='{% url 'login_app:register' %}'>Registration</a></li>

                    {% if user.is_authenticated %}
                    <li><a class='navbar-link' href='{% url 'user_logout' %}'>Logout</a></li>
                    {% else %}
                    <li><a class='navbar-link' href='{% url 'login_app:user_login' %}'>Login</a></li>
                    {% endif %}
                </ul>
            
            </div>
        </nav>
        
        <div class='container'>
            {% block body_block %}

            {% endblock %}
        </div>
    </body>
</html>

login/templates/loginapp/index.html
{% extends "loginapp/base.html" %}
{% block body_block%}
<div class='jumbotron'>
    <h1>Welcom to Home Page!</h1>
</div>
{% endblock %}

login/templates/loginapp/login.html
{% extends "loginapp/base.html" %}
{% block body_block%}
<div class='jumbotron'>
    <h1>Login Here!</h1>
    <form action="{% url 'login_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username : </label>
        <input type=text name="username" placeholder="Enter Username">

        <label for="password">Password : </label>
        <input type=password name="password">

        <input type=submit value='Login'>
    </form>

</div>
{% endblock %}

login/templates/loginapp/registration.html
{% extends "loginapp/base.html" %}
{% load static %}

{% block body_block%}
<div class='jumbotron'>
    {% if registered %}
      <h1>Thank You!</h1>
    {% else %}
      <h1>Fill out the Registration Form</h1>
      <form enctype='multipart/form-data' method='POST'>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type='submit' name="" value='Register'>
      </form>
    {% endif %}
</div>
{% endblock %}